config/routes.rb
Rails.application.routes.draw do
  get 'packages/search', to: 'packages#search'
  resources :packages, only: [:index, :show]
  get 'person/search', to: 'person#search'
  resources :person, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get 'search', to: 'home#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  ITEMS_PER_PAGE = 50
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :package_version
  belongs_to :person
end

app/models/concerns/fuzzy_searchable.rb
module FuzzySearchable
  def fuzzy_search(string)
    parsed_string = "%#{string.downcase}%"
    searchable_attributes = self::FUZZY_SEARCHABLE_ATTRIBUTES
    return self.all if searchable_attributes.length == 0

    query = self.where("lower(#{searchable_attributes[0]}) LIKE ?", parsed_string)

    if searchable_attributes.length > 1
      searchable_attributes[1..-1].each do |attribute|
        query.or(self.where("lower(#{attribute}) LIKE ?", parsed_string))
      end
    end

    query
  end
end

app/models/package.rb
class Package < ApplicationRecord
  extend FuzzySearchable

  paginates_per ITEMS_PER_PAGE

  FUZZY_SEARCHABLE_ATTRIBUTES = ['title']

  has_many :package_versions
  belongs_to :latest_package_version, class_name: 'PackageVersion', foreign_key: 'latest_package_version_id', optional: true
end

app/models/package_version.rb
class PackageVersion < ApplicationRecord
  extend FuzzySearchable

  CREATED_STATUS = 'created'
  COMPLETED_STATUS = 'completed'

  belongs_to :package
  belongs_to :maintainer, class_name: 'Person', foreign_key: :maintainer_id, optional: true

  has_many :authors
  has_many :person, through: :authors
end

app/models/person.rb
class Person < ApplicationRecord
  extend FuzzySearchable

  paginates_per ITEMS_PER_PAGE

  FUZZY_SEARCHABLE_ATTRIBUTES = ['name', 'email']

  has_many :authors
  has_many :package_versions, through: :authors
  has_many :maintains, class_name: 'PackageVersion', foreign_key: :maintainer_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  SEARCH_PAGE_QUERY_LIMIT = 10
  def index; end

  def search
    query = params[:q]
    @people = Person.fuzzy_search(query).order(:name).limit(SEARCH_PAGE_QUERY_LIMIT)
    @packages = Package.fuzzy_search(query).order(:title).limit(SEARCH_PAGE_QUERY_LIMIT)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @packages_length = Package.all.length
    @packages = Package.all.page params[:page]
  end

  def search
    query = params[:q] || ''
    @packages = Package.fuzzy_search(query)
    @packages_length = @packages.length
    @packages = @packages.order(:title).page params[:page]
  end

  def show
    @package = Package.includes(latest_package_version: [:maintainer, authors: :person], package_versions: [authors: :person]).find(params[:id])
    @latest_version = @package.latest_package_version
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
    @people_length = Person.all.length
    @people = Person.all.order(:name).page params[:page]
  end

  def search
    query = params[:q] || ''
    @people = Person.fuzzy_search(query)
    @people_length = @people.length
    @people = @people.order(:name).page params[:page]
  end

  def show
    @person = Person.includes([:maintains, :package_versions, authors: [package_version: [:package]]]).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.container
  .row
    .col
      h2 Search R Packages
      = render 'home/shared/search_bar', url: '/search'

app/views/home/search.html.slim
.container
  .row
    .col
      h3 People
      table.table
        tr
          th Name
        - @people.each do |person|
          tr
            td = link_to person.name, url_for(person)
        tr
          td
            = link_to "Click to see more result", person_search_path(q: params[:q])

      h3 Packages
      table.table
        tr
          th Name
        - @packages.each do |package|
          tr
            td = link_to package.title, url_for(package)
        tr
          td
            = link_to "Click to see more result", packages_search_path(q: params[:q])

app/views/home/shared/_search_bar.html.slim
= form_with(url: url, method: 'get') do
  = text_field_tag :q, params[:q] || '', required: true, class: 'form-control'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CpanIndex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">CPAN Index</a>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/person/index.html.slim
.container
  .row
    .col
      h2 Search
      = render 'home/shared/search_bar', url: '/person/search'

      hr

      = paginate @people

      hr

      h3 People (#{@people_length})
      table.table
        tr
          th Name
        - @people.each do |person|
          tr
            td = link_to person.name, person

app/views/person/search.html.slim
.container
  .row
    .col
      h2 Search
      = render 'home/shared/search_bar', url: '/person/search'

      hr

      = paginate @people

      hr

      h3 People (#{@people_length})
      table.table
        tr
          th Name
        - @people.each do |person|
          tr
            td = link_to person.name, person

app/views/person/show.html.slim
.container
  .row
    .col
      = link_to "< Person Search Page", packages_search_url

  .row
    .col
      h2 Person: #{@person.name}
      p Email: #{@person.email}

      h3 Maintains

      table.table
        tr
          th Package
          th Version Number
        - @person.maintains.each do |maintain|
          tr
            td = link_to maintain.package.title, maintain.package
            td = maintain.version_number

      h3 Authors
      table.table
        tr
          th Package
          th Version Number
          th Role
        - @person.authors.each do |author|
          tr
            td = link_to author.package_version.package.title, author.package_version.package
            td = author.package_version.version_number
            td = author.role